config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :rooms do
     resources :meetings
  end

  resources :meetings do
    resources :comments

  end

  root 'users#new'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
  has_many :comments

  def start_timestamp
    (start_time - 6.hours).strftime('%b %e, %l:%M %p')
  end

  def end_timestamp
    (end_time - 6.hours).strftime('%b %e, %l:%M %p')
  end

  def meeting_author_email
    user.try(:email)
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessor :poster_image_file_name
  attr_accessor :poster_image_content_type
  attr_accessor :poster_image_file_size
  attr_accessor :poster_image_updated_at

  has_many :meetings
  has_attached_file :image, :styles => {  :medium => "300x300",
                                          :thumb => "100x100>" },
                                          :convert_options => { :all => '-auto-orient' },
                                          :storage => :s3,
                                          :bucket => 'reservatron',
                                          :url =>':s3_domain_url',
                                          :path => ':class/:attachment/:id_partition/:style/:filename',
                                          :default_url => "/images/:style/missing.png"


  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meetings
  has_many :comments
  has_many :meeting_comments, through: :posts, source: :meetings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name, :dob, :favorite_color)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Comment was added.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @comment = Comment.new
    @meeting = Meeting.all
  end

  def index
    @comments = Comment.all

  end

  def show
    @comment = Comment.all
  end



  private

    def comment_params
      params.require(:comment).permit(:body, :user_id, :meeting_id)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def new
    @meeting = Meeting.new
    @room = Room.find(params[:room_id])
  end

  def index
    @meetings = Meeting.all
  end

  def show
    @meeting = Meeting.find(params[:id])
    @user = User.all
    @room = Room.all
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id
    @meeting.room_id = params[:room_id]
    respond_to do |format|
      if @meeting.save
        NotificationMailer.new_meeting(@meeting).deliver_now
        format.html { redirect_to meetings_path, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :room_id, :user_id)
    end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def index
    @rooms = Room.all
    @meetings = Meeting.all
  end

  def edit
    @room = Room.find(params[:id])
  end

  def show
    @room = Room.find(params[:id])
    @meetings = Meeting.all
    @comment = Comment.find(params[:id])
  end



  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @room = Room.find(params[:id])
    @room.update!(room_params)
    redirect_to rooms_path
  end

  def show
  end

  def destroy
  end


  private

    def room_params
      params.require(:room).permit(:image, :name, :description, :location)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:create, :show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        redirect_to user_path
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        redirect_to @user
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :dob, :favorite_color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Add a Comment</h1>

<%= simple_form_for([current_user, @comment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body, required: true, autofocus: true %>
    <%= f.select(:users, @users.id) %>
    <%= f.select :meeting, [Meeting.all.name] %>

  <div class="form-actions">
    <%= f.button :submit, "Add comment" %>
  </div>
<% end %>

app/views/comments/show.html.erb
<h1>Comments</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservatron 5000</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/darkly/bootstrap.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a><%= link_to 'Reservatron 5000', root_path, :class => 'navbar-brand', id: "logo" %></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Logged in as #{current_user.first_name.upcase}",
                  user_path(current_user.id) %></li>
              <li><%= link_to 'Browse rooms', rooms_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path(@user), method: :delete %></li>
              <li><%= link_to 'Book now', new_meeting_path(current_user.id) %></li>
            <% end %>
              <li><%= link_to 'Sign up now!', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
        </div>
      </div>
    </div>
  <div class='row'>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
    <%= yield %>
  </div>
    <footer class="navbar-fixed row">
      <div class="large-12 columns">
        <hr> <p>© Reservatron 5000 Inc.  2015</p>
      </div>
    </footer>
  </body>
</html>

app/views/meetings/index.html.erb
<h1>Index</h1>
this is the meeting index


<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <div class="well well-lg">
        <h2 style="text-align: center">Scheduled Meetings  </h2>
      </div>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Meeting</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Scheduled by</th>
      <th>Location</th>
    </tr>
  </thead>
  <tbody>
  <% @meetings.each do |meeting| %>
    <tr>
      <td><%= meeting.name %></td>
      <td><%= meeting.start_timestamp %></td>
      <td><%= meeting.end_timestamp %></td>
      <td><%= meeting.room_id %></td>
      <td><%= link_to('Leave a Comment', new_meeting_comment_path(current_user, Comment.new), class: "btn btn-primary btn-lg") %></td>
       <td><%= link_to('Read comments', meeting_comments_path(@meetings), class: "btn btn-primary btn-lg") %></td>
      <% end %>
    </tr>
  </tbody>
</table>

    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/meetings/new.html.erb
<h1>Book a meeting</h1>

<%= simple_form_for([@room, @meeting]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs" data-provide='datepicker'>
  <%= f.input :name %>
    <hr>
    <%= f.input :start_time %>
    <hr>
    <%= f.datetime_select :end_time %>
    <hr>
  <div class="form-actions">
    <%= f.button :submit, "Book this meeting" %>
  </div>
<% end %>

app/views/meetings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <div class="well well-lg">
        <h2 style="text-align: center">Scheduled Meetings  </h2>
      </div>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Meeting</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Scheduled by</th>
      <th>Location</th>
    </tr>
  </thead>
  <tbody>
  <% @meetings.each do |meeting| %>
    <tr>
      <td><%= meeting.name %></td>
      <td><%= meeting.start_timestamp %></td>
      <td><%= meeting.end_timestamp %></td>
      <td><%= meeting.room.location %></td>
      <td><%= link_to('Leave a Comment', new_user_comment_path(meeting.id),
            class: "btn btn-primary btn-lg") %></td>
      <% end %>
    </tr>
      <% current_user.comments.each do |comment| %>
        <%= comment.body %>
      <% end %>
    </div>
  </tbody>
</table>

    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/partials/_learn_more.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row well well-lg">
      <div class="centerfy">
        <h1 class="text-center">Nah, just kidding</h1>
        <p class='text-center'>That's all there is. I just think three buttons looks better than two.</p>
          <div class="text-center"
              <div class="btn-group btn-group-justified" role="group" aria-label="...">
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Home' root_path %></button>
                </div>
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Browse rooms', rooms_path %></button>
                </div>
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Sign up now!',
                   new_user_registration_path(@user)%></button>
                </div>
          </div>
        </div>
       </div>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<%= link_to 'Add a room', new_room_path %>
<%= link_to 'Update room',

app/views/rooms/destroy.html.erb
<h1>Rooms#destroy</h1>
<p>Find me in app/views/rooms/destroy.html.erb</p>

app/views/rooms/edit.html.erb
<h1>Edit a room</h1>

<%= simple_form_for @room do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true, autofocus: true %>
    <hr>
    <%= f.input  :location , required: true %>
    <hr>
    <%= f.input :description, required: true %>
    <%= f.file_field :image %>

  <div class="form-actions">
    <%= f.button :submit, "Book this meeting" %>
  </div>
<% end %>

app/views/rooms/index.html.erb
<div class="col-md-2"></div>

  <div class="col-md-10">
  <h1>Browse Rooms</h1>
    <% @rooms.each_slice(3) do |r| %>
      <div class="row">
        <% r.each do |room| %>
          <div class="col-md-3">
            <div class="thumbnail">
              <img src=<%= room.image(:medium) %>
                <div class="caption text-center">
                  <h3><%= room.name.upcase %></h3>
                  <p><%= room.description %></p>
                  <div><%= link_to 'View room', room_path(room.id) %>  </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/rooms/new.html.erb
<h1>Rooms#new</h1>
<p>Find me in app/views/rooms/new.html.erb</p>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">

      <div class="well well-lg">
        <%= @room.location %>
        <h2 style="text-align: center">Scheduled Meetings  </h2>
      </div>
        <% if @meetings != nil %>
          <table class="table table-striped table-hover ">
            <thead>
              <tr>
                <th>Meeting</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Scheduled by</th>
                <th>Location</th>
              </tr>
            </thead>
            <tbody>
            <% @meetings.each do |meeting| %>
              <tr>
                <td><%= meeting.name %></td>
                <td><%= meeting.start_timestamp %></td>
                <td><%= meeting.end_timestamp %></td>
                <td><%= meeting.room.location %></td>
                <td><%= link_to('Leave a Comment', new_meeting_comment_path(meeting.id), class: "btn btn-primary btn-lg") %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
        <% else %>
          <p>There are no meetings scheduled for this room yet
          </p>
        <% end %>
        <div><%= link_to "Book Now!", new_room_meeting_path(params[:id]) %></div>
    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row well well-lg">
      <div class="centerfy">
        <h1 class="text-center">Welcome to Reservatron 5000</h1>
        <p class='text-center'>Your one-stop-shop for conferenceroom reservations</p>
          <div class="text-center"
              <div class="btn-group btn-group-justified" role="group" aria-label="...">
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Book now', new_meeting_path(current_user.id) %></button>
                </div>
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Browse rooms', rooms_path %></button>
                </div>
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Sign up now!',
                   new_user_registration_path %></button>
                </div>
              </div>
          </div>
        </div>
       </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row well well-lg">
      <div class="centerfy">
        <h1 class="text-center">Nah, just kidding</h1>
        <p class='text-center'>That's all there is. I just think three buttons looks better than two.</p>
          <div class="text-center"
              <div class="btn-group btn-group-justified" role="group" aria-label="...">
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Home', root_path %></button>
                </div>
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Browse rooms', rooms_path %></button>
                </div>
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default"><%= link_to 'Sign up now!',
                   new_user_registration_path(@user)%></button>
                </div>
          </div>
        </div>
       </div>
    </div>
  </div>
</div>